### ISSUE TITLE
Geoip wants to get loaded, even if not configured

### ISSUE THREAD

**Issue by lunetics** [geocoder-php/BazingaGeocoderBundle#112]
Hi,

I got the following config for the geocoder:
```yaml
bazinga_geocoder:
    adapter: app.http_adapter_guzzle.geocoder

    providers:
        openstreetmap:
            locale:     "%locale%"
        google_maps:
            locale:     "%locale%"
        bing_maps:
            api_key:    "%api.bing_maps.key%"
            locale:     "%locale%"
        chain:
            providers:
                - openstreetmap
                - google_maps
                - bing_maps
```

Trying php7, somehow the bundle wants to "force load" geoip (the pecl module is not compatible with php7). 

Somehow the AddProviderPass also finds geoip (as shown by xdebug) , but it's not enabled / configured on my side:

![debug](https://cloud.githubusercontent.com/assets/149752/15246934/e9c82b66-1910-11e6-90de-a8ee74736518.png)

Any clue?
