### ISSUE TITLE
How to use ChainProvider in Symfony (using v5) ?

### ISSUE THREAD

**Issue by jbennegent** [geocoder-php/BazingaGeocoderBundle#161]
Hello,

I'm trying to use the ChainProvider for something very simple : chaining Google Maps + Mapquest.

I don't really understand why I get the error : 
`Call to a member function getName() on string
`
Here is my configuration : 
```
bazinga_geocoder:
    profiling: 
        enabled: ~
    fake_ip:
        enabled:              true
        ip:                   127.0.0.1
    providers:
        google_maps:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
            options: 
                api_key: "%google_geocoding_api_key%"
            locale: 'FR'
        map_quest:
            factory: Bazinga\GeocoderBundle\ProviderFactory\MapQuestFactory
            locale: 'FR'
            options: 
                api_key: "%mapquest_geocoding_api_key%"
        chain:
            factory: Bazinga\GeocoderBundle\ProviderFactory\ChainFactory
            options: 
                services: [google_maps,map_quest]  
```
Have I missed something in the documentation ? 
It seems that individually, my providers google_maps and map_quest work well.

Thanks a lot for your help.

Regards

**Comment by Nyholm** [comment]
Thank you for this issue. This should be documented. 

I think you have to do something like: 

```yaml
bazinga_geocoder:
    providers:
        google_maps:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
            options: 
                api_key: "%google_geocoding_api_key%"
            locale: 'FR'
        map_quest:
            factory: Bazinga\GeocoderBundle\ProviderFactory\MapQuestFactory
            locale: 'FR'
            options: 
                api_key: "%mapquest_geocoding_api_key%"
        chain:
            factory: Bazinga\GeocoderBundle\ProviderFactory\ChainFactory
            options: 
                services: ['@bazinga_geocoder.provider.google_maps', '@bazinga_geocoder.provider.map_quest']  
```

> It seems that individually, my providers google_maps and map_quest work well.

Okey, then it will work if you do the following:

```yaml
  chain:
      factory: Bazinga\GeocoderBundle\ProviderFactory\ChainFactory
      options: 
         services: ['@google_maps', '@map_quest']  
```

The magic happens here: https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/DependencyInjection/BazingaGeocoderExtension.php#L169-L180

**Comment by jbennegent** [comment]
Thanks for your quick and accurate answer !

Indeed, I needed to use either
`services: ['@bazinga_geocoder.provider.google_maps', '@bazinga_geocoder.provider.map_quest']  `

or 
`services: ['@google_maps', '@bmap_quest']  ` AND giving aliases to my providers.

Here is a working configuration (for whoever may have the same problem) 
```
bazinga_geocoder:
    profiling: 
        enabled: ~
    fake_ip:
        enabled:              true
        ip:                   127.0.0.1
    providers:
        google_maps:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
            options: 
                api_key: "%google_geocoding_api_key%"
            locale: 'FR'
            aliases:
                - "google_maps"
        map_quest:
            factory: Bazinga\GeocoderBundle\ProviderFactory\MapQuestFactory
            locale: 'FR'
            options: 
                api_key: "%mapquest_geocoding_api_key%"
            aliases:
                - "map_quest"
        chain:
            factory: Bazinga\GeocoderBundle\ProviderFactory\ChainFactory
            options: 
                 services: ['@google_maps', '@map_quest']
```
Again, thanks for such a quick answer !
