### ISSUE TITLE
Using symfony 3.3 cache pool

### ISSUE THREAD

**Issue by gimler** [geocoder-php/BazingaGeocoderBundle#165]
i try to use the symfony framework cache pool but getting an error

```
Type error: Argument 1 passed to Geocoder\Plugin\Plugin\CachePlugin::__construct() must be an instance of Psr\SimpleCache\CacheInterface, instance of Symfony\Component\Cache\Adapter\TraceableAdapter given, called in /app/var/cache/dev/appDevDebugProjectContainer.php on line 556
```

config.yml
```
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis
        pools:
            app.cache.gmap:
                adapter: cache.app
                default_lifetime: 600

bazinga_geocoder:
  providers:
    gmap:
      factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
      cache: 'app.cache.gmap'
      cache_lifetime: 3600
```

symfony 3.3.6
willdurand/geocoder-bundle 5.0.0-beta1

**Comment by Nyholm** [comment]
We use PSR16 (SimpleCache) here. Symfony has not implemented that yet. I think it will come in sf 3.4. 

You may use the https://github.com/php-cache/simple-cache-bridge to fix this.

**Comment by gimler** [comment]
thx it works.

service.yml
```
    app.cache.gmap_simple:
        class: Cache\Bridge\SimpleCache\SimpleCacheBridge
        arguments:
            $cacheItemPool: '@app.cache.gmap'
```
config.yml
```
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis
        pools:
            app.cache.gmap:
                adapter: cache.app
                default_lifetime: 600

bazinga_geocoder:
  providers:
    gmap:
      factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
      cache: 'app.cache.gmap_simple'
      cache_lifetime: 3600
```

**Comment by Nyholm** [comment]
Thank you. Could you add a section about this on this page in the documentation. https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/cache.md

**Comment by ralusnom** [comment]
For me the issue is also there with Symfony 5.2

```
Argument 1 passed to Geocoder\Plugin\Plugin\CachePlugin::__construct() must be an instance of 
Psr\SimpleCache\CacheInterface, instance of Symfony\Component\Cache\Adapter\TraceableAdapter given, called in 
/tmp/cache/dev/ContainerGYqSE8Y/Vince_KernelDevDebugContainer.php on line 2648
``` 

framework.yaml

```
  cache:
    app: cache.adapter.redis
    default_redis_provider: redis://redis:6379
    pools:
      app.cache.gmap:
        adapter: cache.app
        default_lifetime: 600

```

services.yaml

```
  app.simple_cache:
    class: Symfony\Component\Cache\Simple\Psr6Cache
    arguments: ['@app.cache.gmap']
```

bazinga_geocoder.yaml

```
    googlemaps:
      factory:  Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
      cache: 'app.cache.gmap'
      cache_lifetime: 3600

```
