### ISSUE TITLE
Chain provider service definition failure

### ISSUE THREAD

**Issue by rodgermd** [geocoder-php/BazingaGeocoderBundle#168]
![image](https://user-images.githubusercontent.com/1067518/30698339-4dcd1954-9eea-11e7-9c55-ac8d5cfc9c57.png)
![image](https://user-images.githubusercontent.com/1067518/30698360-5ccadef0-9eea-11e7-9a36-7cdd7a7ca327.png)

**Comment by ThePixelDeveloper** [comment]
It's `options.services`

```yaml
chain:
    factory: Bazinga\GeocoderBundle\ProviderFactory\ChainFactory
    options:
        services: []
```
