### ISSUE TITLE
locale is ignored

### ISSUE THREAD

**Issue by klemens-u** [geocoder-php/BazingaGeocoderBundle#191]
Hello, whatever I try, setting the locale is ignored when using a geo ip service like FreeGeoIp or GeoPlugin.

Environment:

* Symfony4
* composer require willdurand/geocoder-bundle geocoder-php/free-geoip-provider php-http/message php-http/curl-client guzzlehttp/psr7
* config/packages/bazinga_geocoder.yaml
```
# See the docs at https://github.com/geocoder-php/BazingaGeocoderBundle
bazinga_geocoder:
    providers:
        free_geo_ip:
            factory: Bazinga\GeocoderBundle\ProviderFactory\FreeGeoIpFactory
            #factory: Bazinga\GeocoderBundle\ProviderFactory\GeoPluginFactory
            locale: de_AT
            aliases:
                - geocoder_free_geo_ip
```
* MyController.php
```
$geoq = GeocodeQuery::create('80.110.176.152')->withLocale('de_AT');
$visitorLocation = $this->geocoder_free_geo_ip->geocodeQuery($geoq)->first();
var_dump($visitorLocation)
```
It always returns "Vienna" instead of "Wien".
