### ISSUE TITLE
Custom vendor location symfony 4

### ISSUE THREAD

**Issue by celsoandrade** [geocoder-php/BazingaGeocoderBundle#194]
Hi,

When I add custom vendor location in composer.json using symfony 4
```json
{
    "config": {
        "bin-dir": "bin",
        "vendor-dir": "/some/dir/vendor"
    },
}
```
symfony starts to throw a message geocoder file not found.
FileLocator.php
The file "/app/vendor/willdurand/geocoder/Dumper" does not exist.
For some reason it ignores vendor-dir from composer.json and search for file in the default vendor dir.

thank you

**Comment by celsoandrade** [comment]
Searching the code I think the problem is here:

```yaml
services:
    Geocoder\Dumper\:
        resource: '%kernel.project_dir%/vendor/willdurand/geocoder/Dumper'
        public: true
        tags: ['bazinga_geocoder.dumper']
```
