### ISSUE TITLE
"bazinga_geocoder.provider.acme" service or alias has been removed or inlined when the container was compiled

### ISSUE THREAD

**Issue by alexeybelyy** [geocoder-php/BazingaGeocoderBundle#196]
Hi,

When I try to initialize bundle v 5.1 in symfony 4, I get the following error:

> The "bazinga_geocoder.provider.acme" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

bazinga_geocoder.yaml:

```
bazinga_geocoder:
    fake_ip: 123.123.123.123
    providers:
        acme:
          factory: Bazinga\GeocoderBundle\ProviderFactory\YandexFactory
```
Controller:

```
        $result = $this->container
            ->get('bazinga_geocoder.provider.acme')
            ->geocodeQuery(GeocodeQuery::create('London'));
```

What could be the problem?
