### ISSUE TITLE
"cache.app.simple" service is deprecated since Symfony 4.3

### ISSUE THREAD

**Issue by BigMichi1** [geocoder-php/BazingaGeocoderBundle#276]
Hello,

I'm not quite sure if this belongs to the bundle or the geocoder itself. Still i will try to explain the issue. i configured the geocoder in the way in the yaml file shown below. Since symfony 4.3 i'm getting this deprecation warning that i should use "cache.app" instead of "cache.app.simple". 

``The "Psr\SimpleCache\CacheInterface" / "cache.app.simple" service is deprecated since Symfony 4.3. Use "Symfony\Contracts\Cache\CacheInterface" / "cache.app" instead.``

When i change it, it will result in 

``TypeError : Argument 1 passed to Geocoder\Plugin\Plugin\CachePlugin::__construct() must be an instance of Psr\SimpleCache\CacheInterface, instance of Symfony\Component\Cache\Adapter\TraceableAdapter given, called in var/cache/test/ContainerJ5I8t88/srcApp_KernelTestDebugContainer.php on line 4494
``

    bazinga_geocoder:
      fake_ip: 123.123.123.123
      providers:
        acme:
          factory: Bazinga\GeocoderBundle\ProviderFactory\ArcGISOnlineFactory
          cache: 'cache.app.simple'
          cache_lifetime: 3600

**Comment by norkunas** [comment]
Hello, would this work for you?:

```
bazinga_geocoder:
  fake_ip: 123.123.123.123
  providers:
    acme:
      factory: Bazinga\GeocoderBundle\ProviderFactory\ArcGISOnlineFactory
      cache: 'geocoder.result_cache_provider'
      cache_lifetime: 3600

services:
    geocoder.result_cache_provider:
        class: Symfony\Component\Cache\Psr16Cache
        public: false
        arguments:
            - '@geocoder.result_cache_pool'

framework:
    cache:
        pools:
            geocoder.result_cache_pool:
                adapter: cache.app
```
