### ISSUE TITLE
Allow faking other local ips, not just 127.0.0.1

### ISSUE THREAD

**Issue by teo-sk** [geocoder-php/BazingaGeocoderBundle#282]
I'm using symfony in a dockerized local environment using an older Docker setup on Windows, where it's using a VM. So my local IP is 192.168.99.1 and not 127.0.0.1

in `Resources\config\services.yml`:

```yaml
    Bazinga\GeocoderBundle\Plugin\FakeIpPlugin:
        class: Bazinga\GeocoderBundle\Plugin\FakeIpPlugin
        arguments: ['127.0.0.1', ~, false]
```

the local IP argument should be configurable for this case.
