### ISSUE TITLE
Cache not refreshed when we change the fake_ip value in config

### ISSUE THREAD

**Issue by ruano-a** [geocoder-php/BazingaGeocoderBundle#334]
```
bazinga_geocoder:
    fake_ip: 
        local_ip: ::1
        ip: 123.123.123.123
    providers:
        geoPlugin:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GeoPluginFactory
            cache: 'app.simple_cache'
            cache_lifetime: 3600
            cache_precision: ~
```

In this example, if I change 123.123.123.123 to anything else, the cache is hit and not refreshed.
I assume it's because what GeocodeQuery::create() receives as an argument is the same as before ('127.0.01', or '::1' in my case)

By its nature, it's a dev env issue only.
