### ISSUE TITLE
Support for GoogleMapsBusinessProvider in the bundle config

### ISSUE THREAD

**Issue by zavan** [geocoder-php/BazingaGeocoderBundle#53]
Hi,

I see there is no support for the GoogleMapsBusinessProvider via the bazinga_geocoder.providers configuration.

Right now I'm using this as a fix:

``` yaml
services:
    bazinga_geocoder.http_adapter.buzz:
        class: Geocoder\HttpAdapter\BuzzHttpAdapter

    bazinga_geocoder.provider.google_maps_business:
        class: Geocoder\Provider\GoogleMapsBusinessProvider
        arguments: [@bazinga_geocoder.http_adapter.buzz, "gme-client-id", "private-key"]
```

Then in the Controller:

``` php
$geocoder = $this->get('bazinga_geocoder.geocoder');

$geocoder->registerProvider($this->get('bazinga_geocoder.provider.google_maps_business'));

$result = $geocoder->using('google_maps_business')->geocode('Rua Santo Henrique, 916');
```

But I would love to see this:

``` yaml
bazinga_geocoder:
    providers:
        google_maps_business:
            client_id: ""
            private_key: ""
```

and then in the Controller:

``` php
$result = $this->get('bazinga_geocoder.geocoder')->using('google_maps_business')->geocode('Rua Santo Henrique, 916');
```

I would love to help with that, but I'm kinda of a GitHub newbie, if you guys could teach me the necessary steps I'd apreciate. :D
