### ISSUE TITLE
"The GoogleMapsProvider does not support IP addresses."

### ISSUE THREAD

**Issue by cassianotartari** [geocoder-php/BazingaGeocoderBundle#80]
Hello.

   I'm trying to understand this bundle, I would like to know at least the city from the users by IP address. 

   What I did:

``` yml
bazinga_geocoder:
    providers:
        google_maps: ~
    fake_ip:  150.162.121.63
```

``` php
$result = $this->container
            ->get('bazinga_geocoder.geocoder')
            ->geocode($request->server->get('REMOTE_ADDR'));
```

It returns:

```
The GoogleMapsProvider does not support IP addresses. 
```

What I'm doing wrong? What is the best provider for this propose?

I've checked the ip address over maxmind page and it is returning the right city.

Thanks!
